### ISSUE TITLE
Send a standup note directly to a Mattermost channel

### ISSUE THREAD

**Issue by mikemartino** [mikemartino/standup_notes#18]
Instead of copying and pasting the note into Mattermost (which most of us are doing), we should just be able to shoot it directly over to Mattermost. Some ideas:

1. Use a Python Mattermost library.
2. Pipe the current output of `standup-notes` to [Matterhorn](https://github.com/matterhorn-chat/matterhorn).

**Comment by jcorrive** [comment]
Isn't the Notification Service working on being able to send messages to Mattermost? Could we just send it there and have it do the rest?

**Comment by mikemartino** [comment]
@monicaruttle and I talked about exactly that. The only problem is now we've been asked to hold off on integrating those work based components with anything else. I'm also guessing that this will be a couple of API calls, and it'll be done anyways.
