### ISSUE TITLE
Add bash completion for CLI

### ISSUE THREAD

**Issue by mikemartino** [mikemartino/standup_notes#22]
Add bash completion for the CLI. I don't know anything about them except for they go under _/etc/bash_completion.d/_ and suggest arguments to the user when they hit `tab`.

**Comment by jcorrive** [comment]
There's a package I found that does bash completion for you when using the python arg parser. I don't exactly know how it works but it seems pretty simple.

**Comment by mikemartino** [comment]
> There's a package I found that does bash completion for you when using the python arg parser. I don't exactly know how it works but it seems pretty simple.

If you find it, definitely put it in here. Thanks!

**Comment by jcorrive** [comment]
https://pypi.org/project/argcomplete/
