### ISSUE TITLE
Add the date of the note to the top of the page

### ISSUE THREAD

**Issue by mikemartino** [mikemartino/standup_notes#8]
It's hard to tell what day you're editing unless you can see the filename somewhere (depends on the editor).

We should add something (friendly) at the top of each note. It would also clarify that you're editing next Monday's note on a Friday.

```
Date: Friday April 3rd, 2020
```

**Comment by MarcDonovan1** [comment]
In the dev branch, the date is inserted after the first initial edit of a note.
