### ISSUE TITLE
Add argument to prune old notes

### ISSUE THREAD

**Issue by mikemartino** [mikemartino/standup_notes#9]
Add an argument to prune away old notes. It can be as simple as:

```
standup-notes --delete-notes +10d
```

Add a warning before deleting the notes:
> Are you sure you want to delete the following list of notes (y/N): _
>   /home/mike/Desktop/standup-notes/20200326.standup-notes.txt
>   /home/mike/Desktop/standup-notes/20200323.standup-notes.txt
>   /home/mike/Desktop/standup-notes/20200324.standup-notes.txt

**Comment by MarcDonovan1** [comment]
Added this to the dev branch. Input date that deletes notes older than date inserted

`standup-notes --delete-notes 20200509`
